version: '3.8'
services:
  joomla:
    container_name: ${APP_CONTAINER_NAME}
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: deviljin-daemon:3.8.2-composer
    ports:
      - '8080:80'
    restart: always
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_USER: ${LOCAL_MYSQL_USER}
      JOOMLA_DB_PASSWORD: ${LOCAL_MYSQL_PASSWORD}
      JOOMLA_DB_NAME: ${LOCAL_MYSQL_DATABASE}
      JOOMLA_SITE_NAME: Tonic
      JOOMLA_ADMIN_USER: Jin FromScratch
      JOOMLA_ADMIN_USERNAME: admin
      JOOMLA_ADMIN_PASSWORD: password
      JOOMLA_ADMIN_EMAIL: joomla@example.com
    volumes:
      - '${LOCAL_PROJECT_PATH}:/var/www/html'
    networks:
      - joomla_network

  db:
    image: mariadb:10.11.11
    restart: always
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - '3333:3306'
    environment:
      MYSQL_DATABASE: ${LOCAL_MYSQL_DATABASE}
      MYSQL_USER: ${LOCAL_MYSQL_USER}
      MYSQL_PASSWORD: ${LOCAL_MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - '${LOCAL_DB_PATH}:/var/lib/mysql'
    networks:
      - joomla_network

networks:
  joomla_network:

volumes:
  db_data: